# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duh < Formula
  desc "duh - a minimalist Docker UI that doesn't get in your way."
  homepage "https://github.com/yarlson/duh"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/duh/releases/download/0.1.0/duh_0.1.0_darwin_amd64.tar.gz"
      sha256 "85bf56e6c1e6b0678eb8b588f679fc88b9c41302754f3dadabe1cb856a6c973c"

      def install
        bin.install "duh"
      end
    end
    on_arm do
      url "https://github.com/yarlson/duh/releases/download/0.1.0/duh_0.1.0_darwin_arm64.tar.gz"
      sha256 "abb51af5097f079ab7cc0509a2bc48eb6471f40f5feb9eec1638d6d5a5e857eb"

      def install
        bin.install "duh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/duh/releases/download/0.1.0/duh_0.1.0_linux_amd64.tar.gz"
        sha256 "c64b862a7c1fd97d123d8977430909f549846463518133282be306fa94ec7d03"

        def install
          bin.install "duh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/duh/releases/download/0.1.0/duh_0.1.0_linux_arm64.tar.gz"
        sha256 "cf21ca3e709a4139ac3a43c8b4876e53e13c67f18439167c25c02516b0f30137"

        def install
          bin.install "duh"
        end
      end
    end
  end

  test do
    system "#{bin}/duh --version"
  end
end
