# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duh < Formula
  desc "duh - a minimalist Docker UI that doesn't get in your way."
  homepage "https://github.com/yarlson/duh"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/duh/releases/download/0.5.3/duh_0.5.3_darwin_amd64.tar.gz"
      sha256 "95624bffbfc2df8915bf27fd485509a939384984e43f111e597d1aeb95f9bd7a"

      def install
        bin.install "duh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/duh/releases/download/0.5.3/duh_0.5.3_darwin_arm64.tar.gz"
      sha256 "7dadc155ddefd2a6da1f9827438c628ed173a5230f6825ee8427a11ba18f92c6"

      def install
        bin.install "duh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/duh/releases/download/0.5.3/duh_0.5.3_linux_amd64.tar.gz"
        sha256 "4e20f61ed45f2776a6a24014274e393b56dacab1e350a509f129f6499fbc0ea2"

        def install
          bin.install "duh"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/duh/releases/download/0.5.3/duh_0.5.3_linux_arm64.tar.gz"
        sha256 "6d54f0d323ebf069cc716a07f727fa778385175f2b304be1f6b2cd79831294ea"

        def install
          bin.install "duh"
        end
      end
    end
  end

  test do
    system "#{bin}/duh --version"
  end
end
